version: "3.8"

services:
  commande:
    depends_on: [commande_db]
    ports:
      - "80:8080"
    image: maven:3-openjdk-17
    working_dir: /var/www
    command: mvn clean install spring-boot:run
    volumes:
      - ./:/var/www/
  commande_db:
    image: mysql:latest
    expose: [3306]
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
      - MYSQL_DATABASE=commande